# Generated by Django 5.0.2 on 2024-03-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapeApp', '0002_scrapeddata_waze_link_operatinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='operating_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OperatingHours',
        ),
    ]
