# Generated by Django 5.0.2 on 2024-03-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapeApp', '0003_scrapeddata_operating_hours_delete_operatinghours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapedData',
            new_name='Store',
        ),
    ]
