# Generated by Django 5.0.2 on 2024-03-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapeApp', '0004_rename_scrapeddata_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
