# Generated by Django 5.0.3 on 2024-03-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ScrapeApp", "0006_remove_store_operating_hours_operatinghours"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="operating_hours",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="OperatingHours",
        ),
    ]
