# Generated by Django 5.0.3 on 2024-03-31 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ScrapeApp", "0007_store_operating_hours_delete_operatinghours"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=20)),
                ("opening_time", models.CharField(max_length=10)),
                ("closing_time", models.CharField(max_length=10)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ScrapeApp.store",
                    ),
                ),
            ],
        ),
    ]
