# Generated by Django 5.0.3 on 2024-03-31 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ScrapeApp", "0008_operatinghours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="operating_hours",
        ),
    ]
